### ISSUE TITLE
psi4 CCSD(T) D1/D2 diagnostics not reported for open shell case

### ISSUE THREAD

**Issue by ffangliu** [MolSSI/QCEngine#113]
I use the following block of code to do CCSD(T) calculations
```
psi4_atom_task = qcelemental.models.ResultInput (
    molecule= mol,
    driver="energy",
    model= {"method": "ccsd", "basis": "6-31g"},
)
ret=qcengine.compute(psi4_atom_task, "psi4")

ret.dict()['extras']
````

If the `mol` is restricted shell, then the result in 'extras' includes non-zero values of the `CC D1 DIAGNOSTIC` and `CC D2 DIAGNOSTIC`. The example output of water molecule at singlet state is:

```
{'qcvars': {'-D ENERGY': 0.0,
  'CC D1 DIAGNOSTIC': 0.015061336005482073,
  'CC D2 DIAGNOSTIC': 0.12393617164619228,
  'CC NEW D1 DIAGNOSTIC': 0.015061336005482073,
  'CC T1 DIAGNOSTIC': 0.006755831075299291,
  'CCSD CORRELATION ENERGY': -0.13940696350922102,
  'CCSD OPPOSITE-SPIN CORRELATION ENERGY': -0.11488872459315766,
  'CCSD SAME-SPIN CORRELATION ENERGY': -0.02451823891606328,
  'CCSD TOTAL ENERGY': -76.1195648218788,
```

However, if the calculation is for an open shell system,  `CC D1 DIAGNOSTIC` and `CC D2 DIAGNOSTIC` will always be zero regardless of molecule species. I suspect that QCEngine is not parsing out the D1 and D2 values for these calculation, resulting in zero values all the time.

**Comment by loriab** [comment]
hmpf, GH won't let issues be transferred across organizations.

There's no parsing with Psi4, as it already writes out a QCSchema file. So the issue of CC diagnostics is with psi, not QCEngine. If you don't mind, reopen this [there](https://github.com/psi4/psi4/).

**Comment by ffangliu** [comment]
Thanks! I'll reopen it on the psi4 page.
