### ISSUE TITLE
nwchem exe available through zsh but qcengine doesn't notice it until switch to bash

### ISSUE THREAD

**Issue by ahurta92** [MolSSI/QCEngine#184]
My default shell has been zsh but qcengine doesn't recognize my nwchem executable until I switch my shell back to bash.  

Specifically, when I run `qcengine info programs` in zsh, qcengine returns no available programs. When I run the same command in bash, qcengine returns nwchem as I expected.

**Comment by dgasmith** [comment]
Does `shutil.which` work for any executable?

**Comment by ahurta92** [comment]
Yes, I believe it does.  It locates nwchem fine.

**Comment by dgasmith** [comment]
Can you detail this process a bit more? Trying this on OS X with zsh doesn't show issues. Can you list the QCEngine version, OS version, shell version, and the results of `which NWChem` from the command line?

**Comment by loriab** [comment]
we went through all the qcng ver, conda env, and `which` diagnostics a couple days ago. he looks to be set up perfectly. @ahurta92 maybe try variations on [this line](https://github.com/MolSSI/QCElemental/blob/master/qcelemental/util/importing.py#L73) with `python -c` with `zsh` and see if there's a point where it breaks?

**Comment by ahurta92** [comment]
I'm not able to reproduce the bug now.  I think the issue had something to do with the order in which my path was set in my .bashrc and then .zshrc files.  I cleaned up my rc files last week and now qcengine recognizes nwchem while using both zsh and bash.

**Comment by loriab** [comment]
Good! It doesn't strike me as worth pursuing. If it stays away, go ahead and close the issue.
