### ISSUE TITLE
DFTD3 Method error for incorrect atom distances

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCEngine#186]
**Describe the bug**
This is more of a hunch than a hard error. In several cases where jobs were inputted into QCArchive in Angstrom rather than Bohr DFTD3's error return was "Unsuccessful run. Possibly -D variant not available in dftd3 version.".

**Additional context**
It would be good to run this and see if we can break out "atom too close" errors from variant errors.

**Comment by loriab** [comment]
uggh. For dftd3 alone, do you consider using their internal b2a conversion in qcng as a potential fix or an anathema?

**Comment by dgasmith** [comment]
This is a user input error due to a lack of clarity of units. I don't consider this a DFTD3 issue beyond our parser incorrectly pinning a cause to the issue.

**Comment by loriab** [comment]
closed by #194 

If anyone has an input that can trigger this error, please post, and I can try to classify errors further.
