### ISSUE TITLE
Add more tests to check different input types

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCEngine#19]
Since the addition of the Pydantic Models from QCElemental, we will want to add more tests to ensure the different input types to (dict or Pydantic) are checked against.

**Comment by dgasmith** [comment]
I added a test that does some of this now, can you enumerate the tests that you wish to create?

**Comment by Lnaden** [comment]
Hmm. I missed that you had left in some dict inputs and the Pydantic object inputs, This is fine then
