### ISSUE TITLE
Torsiondrive procedure still uses `local_options`

### ISSUE THREAD

**Issue by jthorton** [MolSSI/QCEngine#408]
**Describe the bug**

The torsiondrive procedure still uses the old `local_options` argument when [running individual optimzations](https://github.com/MolSSI/QCEngine/blob/1887e7119e4a4b2fd836cae410227efcfefc4588/qcengine/procedures/torsiondrive.py#L208-L210) this produces warnings even when the user correctly uses the `task_config` argument on the torsiondrive procedure.   

**To Reproduce**

Run any torsiondrive using the `task_config` argument.

**Expected behavior**

Torsiondrive should internally use the `task_config` argument when running optimizations. 

**Additional context**

**Comment by loriab** [comment]
closed by #410 I think
