### ISSUE TITLE
Psi4 version checking

### ISSUE THREAD

**Issue by godotalgorithm** [MolSSI/QCEngine#68]
I installed QCEngine on a machine that had Psi4 v1.2.1 installed through Conda, and it was failing the Psi4-related tests without flagging a recognizable error related to the incompatible Psi4 version.

**Comment by dgasmith** [comment]
We currently only have the check for `psi4 >= 1.2`, I would have though this should work.

This relates back to getting a static testing server where we can test the versions of many programs.

**Comment by loriab** [comment]
These were definitely qcng tests, not psi4 tests failing? As code has migrated btwn psi4 and qca, there's several ways the wrong location could get loaded, and though we fend them off, the 1.2 series isn't in CI anymore. Are there barriers to updating to the 1.3 series?

**Comment by godotalgorithm** [comment]
I did update to 1.3.1, and I am able to use QCEngine now without any problems. Daniel had suggested that I raise an issue about this anyways as a reminder to fix it.

**Comment by dgasmith** [comment]
This was fixed some time ago.
