### ISSUE TITLE
Incorrect units for molecule xyz in Molpro input

### ISSUE THREAD

**Issue by sjrl** [MolSSI/QCEngine#72]
Molpro reads in the molecule xyz in Angstrom by default and QCElemental provides the coordinates in bohr by default. Therefore, either the XYZ needs to be converted to Angstrom or somehow specify to Molpro that the XYZ is in bohr.

**Comment by sjrl** [comment]
I'm happy to fix this issue, perhaps also using the `to_string` function with a new dtype for Molpro? I'm just raising this issue so I don't forget.

**Comment by loriab** [comment]
this'd be really good to make uniform with Bohr and `to_string`. ping me with any questions.
